---
title: "Economic calendar scraping"
execute:
  echo: false
  eval: true
  output: true
---

```{r}
library(rvest)
library(readr)
library(RSelenium)
library(netstat)
library(tidyverse)
library(lubridate)
library(zoo)
library(data.table)
library(binman)
library(wdman)
```

```{r}
#date to selects
startDate <- "09/02/2024"
endDate <- "11/02/2025"
#Category to select
category <- "#category_employment"
```

```{r}
firefox_path <- "C:/Program Files/Mozilla Firefox/firefox.exe" 


eCaps <- list(
    `moz:firefoxOptions` = list(
        binary = firefox_path
    )
)

selenium_server <- rsDriver(
    browser = "firefox",
    extraCapabilities = eCaps,
    chromever = NULL,
    geckover = "latest",
    phantomver = NULL,
    verbose = TRUE,
    port = 4169L,
    check = FALSE
)
client <- selenium_server$client
```

```{r}
client$navigate("https://www.investing.com/economic-calendar/")
```

```{r}
accept_ccokies_button <- client$findElement(using = "css", "#onetrust-accept-btn-handler")
accept_ccokies_button$clickElement()

button_element <- client$findElement(using = "css", ".popupCloseIcon")
button_element$clickElement()

filter_countries_button <- client$findElement(using = "css", "#filterStateAnchor")
filter_countries_button$clickElement()

deselect_all_button <- client$findElement(using = "css", "#calendarFilterBox_country > div:nth-child(1) > a:nth-child(4)")
deselect_all_button$clickElement()

select_us_button <- client$findElement(using = "css", "#country5")
select_us_button$clickElement()

select_category_button <- client$findElement(using = "css", category)
select_category_button$clickElement()

apply_filter_button <- client$findElement(using = "css", "#ecSubmitButton")
apply_filter_button$clickElement()

select_date_button <- client$findElement(using = "css", "#datePickerToggleBtn")
select_date_button$clickElement()

start_date_input <- client$findElement(using = "css", value = "#startDate")
start_date_input$clearElement()
start_date_input$sendKeysToElement(list(startDate))


end_date_input   <- client$findElement(using = "css", value = "#endDate")
end_date_input$clearElement()
end_date_input$sendKeysToElement(list(endDate))

apply_date_button <- client$findElement(using = "css", "#applyBtn")
apply_date_button$clickElement()

scrolling_script <- "
    let numScrolls = 90;
    for (let i = 0; i < numScrolls; i++) {
        window.scrollTo(0, document.body.scrollHeight);
    }
"
client$executeScript(scrolling_script)
Sys.sleep(5)
```

```{r}
page_source <- client$getPageSource()[[1]]

page <- read_html(page_source)

econ_info <- page |> html_elements("#economicCalendarData") |> html_table()

df <- econ_info[[1]]
df <- df [-8:-9]
```

```{r}
#clean dataframe
days_of_week <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
clean_dataframe <- function(df) {
    helper <- ""
    df <- df[df[, 3] != "Holiday", ]
  for (i in 1:nrow(df)) {
    if (any(grepl(paste(days_of_week, collapse = "|"), df[i, 1], ignore.case = TRUE))) {
      helper <- df[i,1]
    }
    df[i,1] <- paste(helper, " ", df[i,1])
  }
  df <- df[df[, 4] != df[, 5], ]
  return(df)
}

new_df <- clean_dataframe(df)

data_tibble <- as_tibble(new_df)

```

```{r}
client$close()
selenium_server$server$stop()
```